/* Topics generated by tools/import-doc.mjs — review before committing.
   Shape matches CURRICULUM entries in data.js:
   {id, name, note:{keyConcept, points[], mnemonic}, cards[{front,back}], quiz[{q, opts[4], a, explain}]} */
var CUSTOM_CURRICULUM = /* BEGIN-TOPICS */[
  {
    "id": "custom-sagemaker-inference-options-mrpx179v",
    "name": "SageMaker Inference Options",
    "note": {
      "keyConcept": "SageMaker deploys trained models behind endpoints; choose real-time for low latency, serverless for spiky traffic with zero infrastructure, and asynchronous for large payloads and long processing.",
      "points": [
        "Real-time inference serves interactive, low-latency workloads from a persistent endpoint.",
        "Serverless Inference is fully managed with auto-scaling — ideal for traffic with idle periods that can tolerate cold starts.",
        "Asynchronous inference queues requests, handling payloads up to 1 GB and processing times up to one hour.",
        "JumpStart deploys pre-trained catalog models from the Studio UI with no code; ModelBuilder in the Python SDK gives fine-grained control; CloudFormation manages deployments at scale.",
        "SageMaker Neo optimizes models to run efficiently on hardware like AWS Inferentia, cutting compute cost.",
        "Autoscaling adjusts endpoint compute with incoming traffic so you pay only for resources you use."
      ],
      "mnemonic": "RSA at the endpoint: Real-time is Rapid, Serverless is Spiky, Asynchronous is Sizeable — match the letter to your traffic."
    },
    "cards": [
      {
        "front": "Which SageMaker inference option fits interactive, low-latency workloads?",
        "back": "Real-time inference — a persistent endpoint serving immediate predictions."
      },
      {
        "front": "When is SageMaker Serverless Inference the right choice?",
        "back": "Workloads with idle periods between traffic spurts that can tolerate cold starts — no infrastructure to configure or manage."
      },
      {
        "front": "What are the payload and processing limits of asynchronous inference?",
        "back": "Payloads up to 1 GB and processing times up to one hour; requests are queued and processed asynchronously."
      },
      {
        "front": "Which feature deploys pre-trained catalog models from the Studio UI with no complex configuration?",
        "back": "SageMaker JumpStart — ideal for low-code/no-code deployment."
      },
      {
        "front": "What does SageMaker Neo do?",
        "back": "Optimizes trained models to run efficiently on targets like AWS Inferentia, improving performance and reducing compute cost."
      }
    ],
    "quiz": [
      {
        "q": "A model serves requests with 800 MB payloads that take 40 minutes to process. Which inference option fits?",
        "opts": [
          "Real-time inference",
          "Serverless Inference",
          "Asynchronous inference",
          "JumpStart"
        ],
        "a": 2,
        "explain": "Asynchronous inference queues requests and supports payloads up to 1 GB and processing up to an hour."
      },
      {
        "q": "Traffic to your endpoint is idle most of the day with occasional bursts, and cold starts are acceptable. Best option?",
        "opts": [
          "Real-time inference on a large instance",
          "Serverless Inference",
          "Asynchronous inference",
          "Pre-computing results with Neo"
        ],
        "a": 1,
        "explain": "Serverless Inference auto-scales fully managed infrastructure and suits spiky traffic that tolerates cold starts."
      },
      {
        "q": "An experienced data scientist wants fine-grained control (instance types, network isolation) when deploying their own model in Python. Recommended feature?",
        "opts": [
          "JumpStart in Studio",
          "ModelBuilder in the SageMaker Python SDK",
          "CloudFormation templates",
          "SageMaker Neo"
        ],
        "a": 1,
        "explain": "ModelBuilder in the SageMaker Python SDK gives code-level control over deployment settings."
      },
      {
        "q": "What is the primary purpose of SageMaker Neo?",
        "opts": [
          "Queueing large inference requests",
          "Auto-scaling endpoints with traffic",
          "Optimizing models to run efficiently on hardware like AWS Inferentia",
          "Deploying catalog models through a UI"
        ],
        "a": 2,
        "explain": "Neo compiles and optimizes models for better performance on target hardware, minimizing compute costs."
      }
    ]
  }
]/* END-TOPICS */;
